export default {
  INITIAL: "INITIAL",
  ON_TRAVEL_UP: "ON_TRAVEL_UP",
  ON_TRAVEL_DOWN: "ON_TRAVEL_DOWN",
  TRAVEL_ENDED: "TRAVEL_ENDED",
  DOOR_WORKING: "DOOR_WORKING",
  WAITING_FOR_INPUT: "WAITING_FOR_INPUT",
};
